# This file was generated by GoReleaser. DO NOT EDIT.
cask "hexsign" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "56909eb2c872e588cc28e07adb4b8a8f4882d667a6e1900a71d50e8af4995610"
      url "https://github.com/hexsign/hexsign-cli/releases/download/v#{version}/hexsign_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e8bdd1aa376879f97777b88cb4b4d6905a345dbd3b392c27182f6ab8325ea198"
      url "https://github.com/hexsign/hexsign-cli/releases/download/v#{version}/hexsign_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e0ec1624eec132e388f37722ddf92a0c05b3de6ef972e3adaa1a09cbad79e91b"
      url "https://github.com/hexsign/hexsign-cli/releases/download/v#{version}/hexsign_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0eb9f07432a1644cdf0c163cde50a89fcc26cf067a8e6768e3d3571d3751ac22"
      url "https://github.com/hexsign/hexsign-cli/releases/download/v#{version}/hexsign_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hexsign"
  desc "HexSign CLI — manage Apple signing material from your terminal or CI."
  homepage "https://hexsign.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hexsign"

  postflight do
    if OS.mac? && Hardware::CPU.arm?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hexsign"]
    end
  end

  # No zap stanza required

end
