# This file was generated by GoReleaser. DO NOT EDIT.
cask "hexsign" do
  version "0.5.1"

  on_macos do
    on_arm do
      sha256 "59f1025c678ca7341d40f6d8a61bfc56617478ed9981f33d34413015206579fa"
      url "https://github.com/hexsign/hexsign-cli/releases/download/v#{version}/hexsign_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8766370cf8a5d951df568a939627c9485788c23b175e0c86b718005358c6e556"
      url "https://github.com/hexsign/hexsign-cli/releases/download/v#{version}/hexsign_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ad7f76d28279017c8441431ac0ca932b0e88061e8485fdd8936781d591546ea2"
      url "https://github.com/hexsign/hexsign-cli/releases/download/v#{version}/hexsign_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fc040fff070217e9a5bc9a4f326ffa92598b964d91e4c6481426823bd2564433"
      url "https://github.com/hexsign/hexsign-cli/releases/download/v#{version}/hexsign_#{version}_linux_amd64.tar.gz"
    end
  end

  name "hexsign"
  desc "HexSign CLI — manage Apple signing material from your terminal or CI."
  homepage "https://hexsign.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hexsign"

  postflight do
    if OS.mac? && Hardware::CPU.arm?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hexsign"]
    end
  end

  # No zap stanza required
end
