# This file was generated by GoReleaser. DO NOT EDIT.
cask "hexsign" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "0851ad2156cb80a9c8b40bb8622db704eaa5077d233033bb930a79eb23aaad43"
      url "https://github.com/hexsign/hexsign-cli/releases/download/v#{version}/hexsign_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "db6a400dc5623f42e1f738d28e7ef2a7d3cd61398102baabcf824214aab9a0c1"
      url "https://github.com/hexsign/hexsign-cli/releases/download/v#{version}/hexsign_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d7454697972206abf586251b929342a45bc09fd9da0e136b448a4ee9ee7d42b8"
      url "https://github.com/hexsign/hexsign-cli/releases/download/v#{version}/hexsign_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fb708b26aac86b41a79cca557e58d1a043fadfbcc66c54ca400f78aaba73b906"
      url "https://github.com/hexsign/hexsign-cli/releases/download/v#{version}/hexsign_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hexsign"
  desc "HexSign CLI — manage Apple signing material from your terminal or CI."
  homepage "https://hexsign.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hexsign"

  postflight do
    if OS.mac? && Hardware::CPU.arm?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hexsign"]
    end
  end

  # No zap stanza required

end
